### PR TITLE
Reorder Library, t_slv_arr

### PR DESCRIPTION
**Pull request by radonnachie**
Implements the BarrelSwitcher, SquareTransposer, DoubleBuffer and Reorder blocks from the Reorder DSP blockset.

The BarrelSwitcher and SquareTransposer match simulink and have passing testbenches.

The reorder block is still WIP. It operates correctly with the double-buffer under Vivado simulation, but there asides does not perform well. I reckon I need to work with someone who knows what to expect from the block in order to make quick progress forward. It's mostly there, just dotting the 'i's and crossing the 't's.

### CODE REVIEW

**Comment by talonmyburgh** [comment]
@radonnachie shall I proceed with this PR?

**Comment by radonnachie** [comment]
> The reorder block is still WIP. It operates correctly with the double-buffer under Vivado simulation, but there asides does not perform well. I reckon I need to work with someone who knows what to expect from the block in order to make quick progress forward. It's mostly there, just dotting the 'i's and crossing the 't's.

May just want to highlight this somewhere and draw attention to it so I can get feedback on how to fix it.

**Comment by radonnachie** [comment]
@talonmyburgh 
Ready for a merge/squash commit..

**Comment by talonmyburgh** [comment]
Reorder block failing tests - @radonnachie requires assistance on expected DSP operation in order to fix. Merging in the interim.

**Pull request merged**
