### PR TITLE
Munge HDL use Documentation

### PR DESCRIPTION
**Pull request by radonnachie**

### CODE REVIEW

**Comment by radonnachie** [comment]
wait, should I commit the docs folder too... my local compilation shows lots of changes..

**Comment by talonmyburgh** [comment]
Should probably add */docs/build* to the gitignore.

**Comment by radonnachie** [comment]
That's what I thought, but the online RTD seems so outdated... it doesn't have half the delay modules etc...

dark mode is online, light mode is local...
image

If there shouldn't be a build included, then I'll rm the build directory from the repository.

**Comment by talonmyburgh** [comment]
Good point, think my readthedocs webhooks to github expired. Will correct it.

**Pull request merged**
