### PR TITLE
New master

### PR DESCRIPTION
**Pull request by mschiller-nrao**
Fixes timing issue in delay block

### CODE REVIEW

**Comment by mschiller-nrao** [comment]
Still waiting on Timing results, but should be alot better.

**Comment by mschiller-nrao** [comment]
I'm being lazy and only using my VIvado 2022 project for Versal Premium.. But in Versal Premium, that path was failing with a slack at -0.956 pS (550MHz Clock, 1.818nS period)

**Review by talonmyburgh — APPROVED** [review]
Looks good, thanks!

**Comment by mschiller-nrao** [comment]
Afterimplementing the change (about to be pushed) @talonmyburgh That path was no longer the critical path  (instead it was within in the complex multiplier)

and my timing improved to -0.751pS slash suggesting as is in the RfSOC 4x2 the wide-band FFT can run at about 375MHz.

These timing results are for the WBFFT with the following settings:
constant c_fft_test : t_fft :=  (
                                  use_reorder         => false, 
                                  use_fft_shift       => false, 
                                  use_separate        => false,  -- we'll actually use seperate on ngVLA but let's start with complex 
                                  nof_chan            => 0, 
                                  wb_factor           => 4, 
                                  nof_points          => 131072, 
                                  in_dat_w            => 18, 
                                  out_dat_w           => 18, 
                                  out_gain_w          => 0, 
                                  stage_dat_w         => 18, 
                                  twiddle_dat_w       => 18, 
                                  max_addr_w          => c_max_addr_w,
                                  guard_w             => 0,
                                  guard_enable        => true,
                                  stat_data_w         => 56,
                                  stat_data_sz        => 2,
                                  pipe_reo_in_place   => false
                                );

**Pull request merged**
